const toast=document.querySelector('.toast');const field=document.querySelector('.particle-field');let timer;
const messages={start:'旅程已开启 · 颜料正在流动',gallery:'画廊档案将在下一幕展开',settings:'设置面板 · 由运行时接管'};
function burst(btn){const r=btn.getBoundingClientRect();const cx=r.left+r.width*.78,cy=r.top+r.height*.52;for(let i=0;i<18;i++){const p=document.createElement('i');p.className='paint-particle '+(['','gold','cream'][i%3]);p.style.left=cx+'px';p.style.top=cy+'px';p.style.setProperty('--dx',((Math.random()-.5)*170)+'px');p.style.setProperty('--dy',((Math.random()-.68)*130)+'px');p.style.setProperty('--rot',((Math.random()-.5)*420)+'deg');p.style.animationDelay=(i*10)+'ms';field.appendChild(p);setTimeout(()=>p.remove(),900)}}
document.querySelectorAll('.menu-btn').forEach(btn=>{btn.addEventListener('click',()=>{burst(btn);toast.textContent=messages[btn.dataset.action];toast.classList.add('show');clearTimeout(timer);timer=setTimeout(()=>toast.classList.remove('show'),1800)})});
window.addEventListener('keydown',e=>{if(e.key==='Enter'){document.querySelector('.primary').click()}if(e.key==='Escape')toast.classList.remove('show')});
const dropBtn=document.querySelector('#dropBtn'),dropMenu=document.querySelector('#dropMenu');
dropBtn.addEventListener('click',()=>dropMenu.classList.toggle('open'));
dropMenu.querySelectorAll('button').forEach(opt=>opt.addEventListener('click',()=>{dropBtn.querySelector('span').textContent=opt.dataset.filter;dropMenu.classList.remove('open');toast.textContent='筛选：'+opt.dataset.filter;toast.classList.add('show');clearTimeout(timer);timer=setTimeout(()=>toast.classList.remove('show'),1600)}));
const modal=document.querySelector('#modal');document.querySelector('#infoBtn').addEventListener('click',()=>modal.classList.add('show'));document.querySelector('#closeTip').addEventListener('click',()=>modal.classList.remove('show'));modal.addEventListener('click',e=>{if(e.target===modal)modal.classList.remove('show')});
document.querySelector('#search').addEventListener('input',e=>{if(e.target.value){toast.textContent='正在刮开：'+e.target.value;toast.classList.add('show');clearTimeout(timer);timer=setTimeout(()=>toast.classList.remove('show'),1200)}});
